# Microsemi Corp.
# Date: 2020-Nov-09 01:28:27
# This file was generated based on the following SDC source files:
#   C:/Users/Mikey/Desktop/LiberoProjects/PF_Mi_V_Tut/component/work/AXI4_Interconnect/AXI4_Interconnect_0/AXI4_Interconnect.sdc
#   C:/Users/Mikey/Desktop/LiberoProjects/PF_Mi_V_Tut/component/work/CCC_0/CCC_0_0/CCC_0_CCC_0_0_PF_CCC.sdc
#   C:/Users/Mikey/Desktop/LiberoProjects/PF_Mi_V_Tut/component/work/DDR3_0/DDR3_0.sdc
#   C:/Users/Mikey/Desktop/LiberoProjects/PF_Mi_V_Tut/component/work/DDR3_0/CCC_0/DDR3_0_CCC_0_PF_CCC.sdc
#   C:/Users/Mikey/Desktop/LiberoProjects/PF_Mi_V_Tut/component/work/DDR3_0/DLL_0/DDR3_0_DLL_0_PF_CCC.sdc
#

create_clock -name {REF_CLK_0} -period 20 [ get_ports { REF_CLK_0 } ]
create_generated_clock -name {CCC_0_0/CCC_0_0/pll_inst_0/OUT0} -multiply_by 20 -divide_by 9 -source [ get_pins { CCC_0_0/CCC_0_0/pll_inst_0/REF_CLK_0 } ] -phase 0 [ get_pins { CCC_0_0/CCC_0_0/pll_inst_0/OUT0 } ]
create_generated_clock -name {DDR3_0_0/CCC_0/pll_inst_0/OUT0} -multiply_by 6 -source [ get_pins { DDR3_0_0/CCC_0/pll_inst_0/REF_CLK_0 } ] -phase 0 [ get_pins { DDR3_0_0/CCC_0/pll_inst_0/OUT0 } ]
create_generated_clock -name {DDR3_0_0/CCC_0/pll_inst_0/OUT1} -multiply_by 3 -divide_by 2 -source [ get_pins { DDR3_0_0/CCC_0/pll_inst_0/REF_CLK_0 } ] -phase 0 [ get_pins { DDR3_0_0/CCC_0/pll_inst_0/OUT1 } ]
create_generated_clock -name {DDR3_0_0/CCC_0/pll_inst_0/OUT2} -multiply_by 6 -source [ get_pins { DDR3_0_0/CCC_0/pll_inst_0/REF_CLK_0 } ] -phase 0 [ get_pins { DDR3_0_0/CCC_0/pll_inst_0/OUT2 } ]
create_generated_clock -name {DDR3_0_0/CCC_0/pll_inst_0/OUT3} -multiply_by 6 -source [ get_pins { DDR3_0_0/CCC_0/pll_inst_0/REF_CLK_0 } ] -phase 0 [ get_pins { DDR3_0_0/CCC_0/pll_inst_0/OUT3 } ]
set_false_path -through [ get_pins { AXI4_Interconnect_0/ARESETN* } ]
set_false_path -from [ get_cells { AXI4_Interconnect_0/*/SlvConvertor_loop[*].slvcnv/slvCDC/genblk1*/rdGrayCounter*/cntGray* } ] -to [ get_cells { AXI4_Interconnect_0/*/SlvConvertor_loop[*].slvcnv/slvCDC/genblk1*/rdPtr_s1* } ]
set_false_path -from [ get_cells { AXI4_Interconnect_0/*/SlvConvertor_loop[*].slvcnv/slvCDC/genblk1*/wrGrayCounter*/cntGray* } ] -to [ get_cells { AXI4_Interconnect_0/*/SlvConvertor_loop[*].slvcnv/slvCDC/genblk1*/wrPtr_s1* } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/*/I_IOD_*/ARST_N } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_*_CTRL/I_LANECTRL/HS_IO_CLK_PAUSE } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANECTRL_ADDR_CMD_0/I_LANECTRL*/HS_IO_CLK_PAUSE } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/*/I_IOD_*/RX_SYNC_RST* } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/*/I_IOD_*/DELAY_LINE_MOVE } ]
set_false_path -through [ get_pins { DDR3_0_0/DDRPHY_BLK_0/*/I_IOD_*/DELAY_LINE_OUT_OF_RANGE } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DDR_READ } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/RESET } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DELAY_LINE_DIRECTION } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DELAY_LINE_MOVE } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DELAY_LINE_LOAD DDR3_0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DELAY_LINE_SEL } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/SWITCH } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/READ_CLK_SEL[2] } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DLL_CODE[0] } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DLL_CODE[1] } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DLL_CODE[2] } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DLL_CODE[3] } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DLL_CODE[4] } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DLL_CODE[5] } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DLL_CODE[6] } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_0_CTRL/I_LANECTRL/DLL_CODE[7] } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DDR_READ } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/RESET } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DELAY_LINE_DIRECTION } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DELAY_LINE_MOVE } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DELAY_LINE_LOAD DDR3_0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DELAY_LINE_SEL } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/SWITCH } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/READ_CLK_SEL[2] } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DLL_CODE[0] } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DLL_CODE[1] } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DLL_CODE[2] } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DLL_CODE[3] } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DLL_CODE[4] } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DLL_CODE[5] } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DLL_CODE[6] } ]
set_false_path -to [ get_pins { DDR3_0_0/DDRPHY_BLK_0/LANE_1_CTRL/I_LANECTRL/DLL_CODE[7] } ]
set_false_path -through [ get_pins { DDR3_0_0/DDRPHY_BLK_0/*/I_*FEEDBACK*/Y } ]
set_false_path -through [ get_pins { DDR3_0_0/DDRPHY_BLK_0/OB_DIFF_CK0/Y } ]
set_false_path -through [ get_pins { DDR3_0_0/DDRPHY_BLK_0/OB_A_12/Y } ]
set_false_path -through [ get_pins { DDR3_0_0/DDRPHY_BLK_0/*/I_TRIBUFF_*/D } ]
set_false_path -through [ get_pins { DDR3_0_0/DDRPHY_BLK_0/*/I_TRIBUFF_*/E } ]
set_false_path -through [ get_pins { DDR3_0_0/DDRPHY_BLK_0/*/I_BIBUF*/D } ]
set_false_path -through [ get_pins { DDR3_0_0/DDRPHY_BLK_0/*/I_BIBUF*/E } ]
set_false_path -through [ get_pins { DDR3_0_0/DDRPHY_BLK_0/*/I_BIBUF*/Y } ]
set_false_path -through [ get_pins { DDR3_0_0/DDRPHY_BLK_0/*/I_BIBUF_DIFF_DQS_*/YN } ]
set_false_path -to [ get_pins { DDR3_0_0/CCC_0/pll_inst_0/PHASE_OUT0_SEL } ]
set_false_path -to [ get_pins { DDR3_0_0/CCC_0/pll_inst_0/PHASE_OUT2_SEL } ]
set_false_path -to [ get_pins { DDR3_0_0/CCC_0/pll_inst_0/PHASE_OUT3_SEL } ]
set_multicycle_path -setup_only 2 -from [ get_cells { DDR3_0_0/DDRPHY_BLK_0/IOD_TRAINING_0/COREDDR_TIP_INT_U/TIP_CTRL_BLK/u_write_callibrator/select* } ]
